# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2fa36b123e4ddb0f2fc3e89782a6d8a147f18114c8ca064064d0eaedbcaed7596fbec37a1b39bf70f5ec193914c569a37853a49f2e3eba5f1c9a26d0ec0cc65

test:
  secret_key_base: 8416e5ecc623b6c6fac7f9b5a43dbd0334468080eac16b5c43de49d66c58a29092a9870ae85efce7f756d3dedd89a32c9ae1f15bee2d10608d9576fe6ad62e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
